/**
 * API Key 及配置相关的环境变量名常量
 *
 * 集中定义，避免在 providerConfigUtils.ts 和各 *ProviderPresets.ts 中硬编码重复。
 */
export const ENV_KEYS = {
  // Claude / Anthropic
  ANTHROPIC_BASE_URL: "ANTHROPIC_BASE_URL",
  ANTHROPIC_AUTH_TOKEN: "ANTHROPIC_AUTH_TOKEN",
  ANTHROPIC_API_KEY: "ANTHROPIC_API_KEY",
  ANTHROPIC_MODEL: "ANTHROPIC_MODEL",
  ANTHROPIC_DEFAULT_HAIKU_MODEL: "ANTHROPIC_DEFAULT_HAIKU_MODEL",
  ANTHROPIC_DEFAULT_SONNET_MODEL: "ANTHROPIC_DEFAULT_SONNET_MODEL",
  ANTHROPIC_DEFAULT_OPUS_MODEL: "ANTHROPIC_DEFAULT_OPUS_MODEL",

  // Gemini
  GOOGLE_GEMINI_BASE_URL: "GOOGLE_GEMINI_BASE_URL",
  GEMINI_API_KEY: "GEMINI_API_KEY",
  GEMINI_MODEL: "GEMINI_MODEL",

  // Codex
  CODEX_API_KEY: "CODEX_API_KEY",
} as const;
