import type { ProviderCategory } from "../types";

export interface ProviderMetadata {
  name: string;
  nameKey?: string;
  websiteUrl: string;
  apiKeyUrl?: string;
  category?: ProviderCategory;
  isPartner?: boolean;
  partnerPromotionKey?: string;
  icon?: string;
  iconColor?: string;
}

/**
 * 供应商元数据注册表
 *
 * 以供应商 name（转为 camelCase）为 key，聚合所有 *ProviderPresets.ts 中的
 * name / nameKey / websiteUrl / apiKeyUrl / category / isPartner /
 * partnerPromotionKey / icon / iconColor 字段。
 *
 * 当同一供应商在不同预设文件中元数据不一致时，以 claudeProviderPresets.ts 为准。
 */
export const PROVIDER_METADATA: Record<string, ProviderMetadata> = {
  // ===== Official =====
  claudeOfficial: {
    name: "Claude Official",
    websiteUrl: "https://www.anthropic.com/claude-code",
    category: "official",
    icon: "anthropic",
    iconColor: "#D4915D",
  },
  openaiOfficial: {
    name: "OpenAI Official",
    websiteUrl: "https://chatgpt.com/codex",
    category: "official",
    icon: "openai",
    iconColor: "#00A67E",
  },
  googleOfficial: {
    name: "Google Official",
    websiteUrl: "https://ai.google.dev/",
    apiKeyUrl: "https://aistudio.google.com/apikey",
    category: "official",
    icon: "gemini",
    iconColor: "#4285F4",
  },
  claudeDesktopOfficial: {
    name: "Claude Desktop Official",
    websiteUrl: "https://claude.ai/download",
    category: "official",
    icon: "anthropic",
    iconColor: "#D4915D",
  },
  nousResearch: {
    name: "Nous Research",
    websiteUrl: "https://nousresearch.com",
    apiKeyUrl: "https://portal.nousresearch.com/",
    category: "official",
    icon: "hermes",
    iconColor: "#7C3AED",
  },

  // ===== Aggregators =====
  shengsuanyun: {
    name: "Shengsuanyun",
    nameKey: "providerForm.presets.shengsuanyun",
    websiteUrl: "https://www.shengsuanyun.com",
    apiKeyUrl: "https://www.shengsuanyun.com/?from=CH_4HHXMRYF",
    category: "aggregator",
    isPartner: true,
    partnerPromotionKey: "shengsuanyun",
    icon: "shengsuanyun",
  },
  aiHubMix: {
    name: "AiHubMix",
    websiteUrl: "https://aihubmix.com",
    apiKeyUrl: "https://aihubmix.com",
    category: "aggregator",
    icon: "aihubmix",
    iconColor: "#006FFB",
  },
  siliconFlow: {
    name: "SiliconFlow",
    websiteUrl: "https://siliconflow.cn",
    apiKeyUrl: "https://cloud.siliconflow.cn/i/drGuwc9k",
    category: "aggregator",
    isPartner: true,
    partnerPromotionKey: "siliconflow",
    icon: "siliconflow",
    iconColor: "#6E29F6",
  },
  siliconFlowEn: {
    name: "SiliconFlow en",
    websiteUrl: "https://siliconflow.com",
    apiKeyUrl: "https://cloud.siliconflow.cn/i/drGuwc9k",
    category: "aggregator",
    isPartner: true,
    partnerPromotionKey: "siliconflow",
    icon: "siliconflow",
    iconColor: "#000000",
  },
  dmxapi: {
    name: "DMXAPI",
    websiteUrl: "https://www.dmxapi.cn",
    apiKeyUrl: "https://www.dmxapi.cn",
    category: "aggregator",
    isPartner: true,
    partnerPromotionKey: "dmxapi",
  },
  claudeapi: {
    name: "ClaudeAPI",
    websiteUrl: "https://claudeapi.com",
    apiKeyUrl: "https://console.claudeapi.com/register?aff=pCLD",
    category: "aggregator",
    isPartner: true,
    partnerPromotionKey: "claudeapi",
    icon: "claudeapi",
  },
  runapi: {
    name: "RunAPI",
    websiteUrl: "https://runapi.co",
    apiKeyUrl: "https://runapi.co",
    category: "aggregator",
    isPartner: true,
    partnerPromotionKey: "runapi",
    icon: "runapi",
  },
  openRouter: {
    name: "OpenRouter",
    websiteUrl: "https://openrouter.ai",
    apiKeyUrl: "https://openrouter.ai/keys",
    category: "aggregator",
    icon: "openrouter",
    iconColor: "#6566F1",
  },
  theRouter: {
    name: "TheRouter",
    websiteUrl: "https://therouter.ai",
    apiKeyUrl: "https://dashboard.therouter.ai",
    category: "aggregator",
  },
  novitaAi: {
    name: "Novita AI",
    websiteUrl: "https://novita.ai",
    apiKeyUrl: "https://novita.ai",
    category: "aggregator",
    icon: "novita",
    iconColor: "#000000",
  },
  modelScope: {
    name: "ModelScope",
    websiteUrl: "https://modelscope.cn",
    category: "aggregator",
    icon: "modelscope",
    iconColor: "#624AFF",
  },
  compshare: {
    name: "Compshare",
    nameKey: "providerForm.presets.ucloud",
    websiteUrl: "https://www.compshare.cn",
    apiKeyUrl:
      "https://www.compshare.cn/coding-plan?ytag=GPU_YY_YX_git_cc-switch-eco",
    category: "aggregator",
    isPartner: true,
    partnerPromotionKey: "ucloud",
    icon: "ucloud",
    iconColor: "#000000",
  },
  compshareCodingPlan: {
    name: "Compshare Coding Plan",
    nameKey: "providerForm.presets.ucloudCoding",
    websiteUrl: "https://www.compshare.cn",
    apiKeyUrl:
      "https://www.compshare.cn/coding-plan?ytag=GPU_YY_YX_git_cc-switch-eco",
    category: "aggregator",
    isPartner: true,
    partnerPromotionKey: "ucloud",
    icon: "ucloud",
    iconColor: "#000000",
  },
  nvidia: {
    name: "Nvidia",
    websiteUrl: "https://build.nvidia.com",
    apiKeyUrl: "https://build.nvidia.com/settings/api-keys",
    category: "aggregator",
    icon: "nvidia",
    iconColor: "#000000",
  },
  pipellm: {
    name: "PIPELLM",
    websiteUrl: "https://code.pipellm.ai",
    apiKeyUrl: "https://code.pipellm.ai/login?ref=uvw650za",
    category: "aggregator",
    icon: "pipellm",
  },
  togetherAi: {
    name: "Together AI",
    nameKey: "providerForm.presets.together",
    websiteUrl: "https://together.ai",
    apiKeyUrl: "https://api.together.ai/settings/api-keys",
    category: "aggregator",
    icon: "together",
    iconColor: "#0F6FFF",
  },
  newapi: {
    name: "NewAPI",
    websiteUrl: "https://www.newapi.pro",
    icon: "newapi",
    iconColor: "#00A67E",
  },

  // ===== CN Official =====
  volcengineAgentplan: {
    name: "火山Agentplan",
    websiteUrl:
      "https://www.volcengine.com/activity/agentplan?utm_campaign=hw&utm_content=ccswitche&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitche",
    apiKeyUrl:
      "https://www.volcengine.com/activity/agentplan?utm_campaign=hw&utm_content=ccswitche&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitche",
    category: "cn_official",
    isPartner: true,
    partnerPromotionKey: "volcengine_agentplan",
    icon: "huoshan",
    iconColor: "#3370FF",
  },
  bytePlus: {
    name: "BytePlus",
    websiteUrl:
      "https://www.byteplus.com/en/product/modelark?utm_campaign=hw&utm_content=ccswitche&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitche",
    apiKeyUrl:
      "https://www.byteplus.com/en/product/modelark?utm_campaign=hw&utm_content=ccswitche&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitche",
    category: "cn_official",
    isPartner: true,
    partnerPromotionKey: "byteplus",
    icon: "byteplus",
    iconColor: "#3370FF",
  },
  douBaoSeed: {
    name: "DouBaoSeed",
    websiteUrl:
      "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey?apikey=%7B%7D&utm_campaign=hw&utm_content=ccswitche&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitche",
    apiKeyUrl:
      "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey?apikey=%7B%7D&utm_campaign=hw&utm_content=ccswitche&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitche",
    category: "cn_official",
    isPartner: true,
    partnerPromotionKey: "doubaoseed",
    icon: "doubao",
    iconColor: "#3370FF",
  },
  deepSeek: {
    name: "DeepSeek",
    websiteUrl: "https://platform.deepseek.com",
    category: "cn_official",
    icon: "deepseek",
    iconColor: "#1E88E5",
  },
  zhipuGlm: {
    name: "Zhipu GLM",
    websiteUrl: "https://open.bigmodel.cn",
    apiKeyUrl: "https://www.bigmodel.cn/claude-code?ic=RRVJPB5SII",
    category: "cn_official",
    icon: "zhipu",
    iconColor: "#0F62FE",
  },
  zhipuGlmEn: {
    name: "Zhipu GLM en",
    websiteUrl: "https://z.ai",
    apiKeyUrl: "https://z.ai/subscribe?ic=8JVLJQFSKB",
    category: "cn_official",
    icon: "zhipu",
    iconColor: "#0F62FE",
  },
  baiduQianfan: {
    name: "Baidu Qianfan Coding Plan",
    websiteUrl: "https://cloud.baidu.com/product/qianfan_modelbuilder",
    apiKeyUrl:
      "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
    category: "cn_official",
    icon: "baidu",
    iconColor: "#2932E1",
  },
  bailian: {
    name: "Bailian",
    websiteUrl: "https://bailian.console.aliyun.com",
    category: "cn_official",
    icon: "bailian",
    iconColor: "#624AFF",
  },
  bailianForCoding: {
    name: "Bailian For Coding",
    websiteUrl: "https://bailian.console.aliyun.com",
    category: "cn_official",
    icon: "bailian",
    iconColor: "#624AFF",
  },
  kimi: {
    name: "Kimi",
    websiteUrl: "https://platform.moonshot.cn/console",
    category: "cn_official",
    icon: "kimi",
    iconColor: "#6366F1",
  },
  kimiForCoding: {
    name: "Kimi For Coding",
    websiteUrl: "https://www.kimi.com/code/docs/",
    category: "cn_official",
    icon: "kimi",
    iconColor: "#6366F1",
  },
  stepFun: {
    name: "StepFun",
    websiteUrl: "https://platform.stepfun.com/step-plan",
    apiKeyUrl: "https://platform.stepfun.com/interface-key",
    category: "cn_official",
    icon: "stepfun",
    iconColor: "#16D6D2",
  },
  stepFunEn: {
    name: "StepFun en",
    websiteUrl: "https://platform.stepfun.ai/step-plan",
    apiKeyUrl: "https://platform.stepfun.ai/interface-key",
    category: "cn_official",
    icon: "stepfun",
    iconColor: "#16D6D2",
  },
  katCoder: {
    name: "KAT-Coder",
    websiteUrl: "https://console.streamlake.ai",
    apiKeyUrl: "https://console.streamlake.ai/console/api-key",
    category: "cn_official",
    icon: "catcoder",
  },
  longcat: {
    name: "Longcat",
    websiteUrl: "https://longcat.chat/platform",
    apiKeyUrl: "https://longcat.chat/platform/api_keys",
    category: "cn_official",
    icon: "longcat",
    iconColor: "#29E154",
  },
  miniMax: {
    name: "MiniMax",
    websiteUrl: "https://platform.minimaxi.com",
    apiKeyUrl: "https://platform.minimaxi.com/subscribe/coding-plan",
    category: "cn_official",
    isPartner: true,
    partnerPromotionKey: "minimax_cn",
    icon: "minimax",
    iconColor: "#FF6B6B",
  },
  miniMaxEn: {
    name: "MiniMax en",
    websiteUrl: "https://platform.minimax.io",
    apiKeyUrl: "https://platform.minimax.io/subscribe/coding-plan",
    category: "cn_official",
    isPartner: true,
    partnerPromotionKey: "minimax_en",
    icon: "minimax",
    iconColor: "#FF6B6B",
  },
  baiLing: {
    name: "BaiLing",
    websiteUrl: "https://alipaytbox.yuque.com/sxs0ba/ling/get_started",
    category: "cn_official",
  },
  xiaomiMiMo: {
    name: "Xiaomi MiMo",
    websiteUrl: "https://platform.xiaomimimo.com",
    apiKeyUrl: "https://platform.xiaomimimo.com/#/console/api-keys",
    category: "cn_official",
    icon: "xiaomimimo",
    iconColor: "#000000",
  },
  xiaomiMiMoTokenPlan: {
    name: "Xiaomi MiMo Token Plan (China)",
    websiteUrl: "https://platform.xiaomimimo.com/#/token-plan",
    apiKeyUrl: "https://platform.xiaomimimo.com/#/console/plan-manage",
    category: "cn_official",
    icon: "xiaomimimo",
    iconColor: "#000000",
  },

  // ===== Third Party =====
  patewayAi: {
    name: "PatewayAI",
    websiteUrl: "https://pateway.ai",
    apiKeyUrl: "https://pateway.ai/?ch=etzpm8&aff=WB6M6F67#/",
    category: "third_party",
    isPartner: true,
    partnerPromotionKey: "patewayai",
    icon: "pateway",
  },
  geminiNative: {
    name: "Gemini Native",
    websiteUrl: "https://ai.google.dev/gemini-api",
    apiKeyUrl: "https://aistudio.google.com/app/apikey",
    category: "third_party",
    icon: "gemini",
    iconColor: "#4285F4",
  },
  openCodeGoDeepSeek: {
    name: "OpenCode Go (DeepSeek V4 Flash)",
    websiteUrl: "https://opencode.ai",
    category: "third_party",
    icon: "opencode",
    iconColor: "#211E1E",
  },
  relaxyCode: {
    name: "RelaxyCode",
    websiteUrl: "https://www.relaxycode.com",
    apiKeyUrl: "https://www.relaxycode.com/register",
    category: "third_party",
    icon: "relaxcode",
  },
  cubence: {
    name: "Cubence",
    websiteUrl: "https://cubence.com",
    apiKeyUrl: "https://cubence.com/signup?code=CCSWITCH&source=ccs",
    category: "third_party",
    isPartner: true,
    partnerPromotionKey: "cubence",
    icon: "cubence",
    iconColor: "#000000",
  },
  aiGoCode: {
    name: "AIGoCode",
    websiteUrl: "https://aigocode.com",
    apiKeyUrl: "https://aigocode.com/invite/CC-SWITCH",
    category: "third_party",
    isPartner: true,
    partnerPromotionKey: "aigocode",
    icon: "aigocode",
    iconColor: "#5B7FFF",
  },
  rightCode: {
    name: "RightCode",
    websiteUrl: "https://www.right.codes",
    apiKeyUrl: "https://www.right.codes/register?aff=CCSWITCH",
    category: "third_party",
    isPartner: true,
    partnerPromotionKey: "rightcode",
    icon: "rc",
    iconColor: "#E96B2C",
  },
  aiCodeMirror: {
    name: "AICodeMirror",
    websiteUrl: "https://www.aicodemirror.com",
    apiKeyUrl: "https://www.aicodemirror.com/register?invitecode=9915W3",
    category: "third_party",
    isPartner: true,
    partnerPromotionKey: "aicodemirror",
    icon: "aicodemirror",
    iconColor: "#000000",
  },
  crazyRouter: {
    name: "CrazyRouter",
    websiteUrl: "https://www.crazyrouter.com",
    apiKeyUrl:
      "https://www.crazyrouter.com/register?aff=OZcm&ref=cc-switch-eco",
    category: "third_party",
    isPartner: true,
    partnerPromotionKey: "crazyrouter",
    icon: "crazyrouter",
    iconColor: "#000000",
  },
  sssAiCode: {
    name: "SSSAiCode",
    websiteUrl: "https://www.sssaicode.com",
    apiKeyUrl: "https://www.sssaicode.com/register?ref=DCP0SM",
    category: "third_party",
    isPartner: true,
    partnerPromotionKey: "sssaicode",
    icon: "sssaicode",
    iconColor: "#000000",
  },
  micu: {
    name: "Micu",
    websiteUrl: "https://www.micuapi.ai",
    apiKeyUrl: "https://www.micuapi.ai/register?aff=aOYQ",
    category: "third_party",
    isPartner: true,
    partnerPromotionKey: "micu",
    icon: "micu",
    iconColor: "#000000",
  },
  cTok: {
    name: "CTok.ai",
    websiteUrl: "https://ctok.ai",
    apiKeyUrl: "https://ctok.ai",
    category: "third_party",
    isPartner: true,
    partnerPromotionKey: "ctok",
    icon: "ctok",
    iconColor: "#000000",
  },
  eFlowCode: {
    name: "E-FlowCode",
    websiteUrl: "https://e-flowcode.cc",
    apiKeyUrl: "https://e-flowcode.cc",
    category: "third_party",
    icon: "eflowcode",
    iconColor: "#000000",
  },
  githubCopilot: {
    name: "GitHub Copilot",
    websiteUrl: "https://github.com/features/copilot",
    category: "third_party",
    icon: "github",
    iconColor: "#000000",
  },
  codex: {
    name: "Codex",
    websiteUrl: "https://openai.com/chatgpt/pricing",
    category: "third_party",
    icon: "openai",
    iconColor: "#000000",
  },
  lemonData: {
    name: "LemonData",
    websiteUrl: "https://lemondata.cc",
    apiKeyUrl: "https://lemondata.cc/r/FFX1ZDUP",
    category: "third_party",
    isPartner: true,
    partnerPromotionKey: "lemondata",
    icon: "lemondata",
  },
  packyCode: {
    name: "PackyCode",
    websiteUrl: "https://www.packyapi.com",
    apiKeyUrl: "https://www.packyapi.com/register?aff=cc-switch-eco",
    category: "third_party",
    isPartner: true,
    partnerPromotionKey: "packycode",
    icon: "packycode",
  },
  claudecn: {
    name: "ClaudeCN",
    websiteUrl: "https://claudecn.top",
    apiKeyUrl: "https://claudecn.top/register?aff=ccswitche",
    category: "third_party",
    isPartner: true,
    partnerPromotionKey: "claudecn",
    icon: "claudecn",
  },
  azureOpenai: {
    name: "Azure OpenAI",
    websiteUrl:
      "https://learn.microsoft.com/en-us/azure/ai-foundry/openai/how-to/codex",
    category: "third_party",
    icon: "azure",
    iconColor: "#0078D4",
  },

  // ===== Cloud Provider =====
  awsBedrockAksk: {
    name: "AWS Bedrock (AKSK)",
    websiteUrl: "https://aws.amazon.com/bedrock/",
    category: "cloud_provider",
    icon: "aws",
    iconColor: "#FF9900",
  },
  awsBedrockApiKey: {
    name: "AWS Bedrock (API Key)",
    websiteUrl: "https://aws.amazon.com/bedrock/",
    category: "cloud_provider",
    icon: "aws",
    iconColor: "#FF9900",
  },
  awsBedrock: {
    name: "AWS Bedrock",
    websiteUrl: "https://aws.amazon.com/bedrock/",
    category: "cloud_provider",
    icon: "aws",
    iconColor: "#FF9900",
  },

  // ===== Custom =====
  customGemini: {
    name: "自定义",
    websiteUrl: "",
    category: "custom",
  },
  openaiCompatible: {
    name: "OpenAI Compatible",
    websiteUrl: "",
    category: "custom",
    icon: "generic",
    iconColor: "#6B7280",
  },
  customGateway: {
    name: "自定义网关",
    websiteUrl: "",
    icon: "openai",
    iconColor: "#6366F1",
  },

  // ===== OMO =====
  ohMyOpenCode: {
    name: "Oh My OpenCode",
    websiteUrl: "https://github.com/code-yeongyu/oh-my-openagent",
    category: "omo",
    icon: "opencode",
    iconColor: "#8B5CF6",
  },
  ohMyOpenCodeSlim: {
    name: "Oh My OpenCode Slim",
    websiteUrl: "https://github.com/alvinunreal/oh-my-opencode-slim",
    category: "omo-slim",
    icon: "opencode",
    iconColor: "#6366F1",
  },

  // ===== OpenCode-only presets =====
  stepFunStepPlan: {
    name: "StepFun Step Plan",
    websiteUrl: "https://platform.stepfun.com/docs/zh/step-plan/overview",
    apiKeyUrl: "https://platform.stepfun.com/interface-key",
    category: "cn_official",
    icon: "stepfun",
    iconColor: "#005AFF",
  },
  qwenCoder: {
    name: "Qwen Coder",
    websiteUrl: "https://bailian.console.aliyun.com",
    apiKeyUrl: "https://bailian.console.aliyun.com/#/api-key",
    category: "cn_official",
    icon: "qwen",
    iconColor: "#FF6A00",
  },
  kimiK26: {
    name: "Kimi k2.6",
    websiteUrl: "https://platform.moonshot.cn/console",
    apiKeyUrl: "https://platform.moonshot.cn/console/api-keys",
    category: "cn_official",
    icon: "kimi",
    iconColor: "#6366F1",
  },
};
